name: Update Neon DB with Migrations

on:
  push:
    paths:
      - "ctf/migrations/**"
      - ".github/workflows/update-neon-db.yml"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd ctf
          pnpm install

      - name: Run Drizzle Migrations
        env:
          DATABASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.NEON_DATABASE_URL_PROD || secrets.NEON_DATABASE_URL_STAGING }}
        run: |
          cd ctf
          pnpm drizzle-kit push:pg
